---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	validate_input(validate_input)
	retrieve(retrieve)
	generate(generate)
	verify(verify)
	expand_query(expand_query)
	refuse(refuse)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> validate_input;
	expand_query --> retrieve;
	generate --> verify;
	refuse --> finalize;
	retrieve -.-> generate;
	retrieve -.-> refuse;
	validate_input -.-> refuse;
	validate_input -.-> retrieve;
	verify -.-> expand_query;
	verify -.-> finalize;
	verify -.-> refuse;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
